### ISSUE TITLE
Mem leak?

### ISSUE THREAD

**Issue by athanp** [vstakhov/rspamd#1332]
I've noticed that normal worker uses 230M when first started, 350 next day and over 500MB in next two days, even though it only scanned less than a dozen text mail messages. (FreeBSD 11, x64, rspamd 1.4.2 whatever config, even default one)
I know this is a difficult to answer question but Is that an expected behavior or a sign of some mem leak?

**Comment by vstakhov** [comment]
I need to check this.

**Comment by vstakhov** [comment]
I don't observe any memory leak in DKIM signing code.

**Comment by athanp** [comment]
FYI I'm not using rspamd DKIM for signing outgoing mail. This worker ram usage increase is noticeable while just staying idle scanning only 5-6 mail per day!
I've configured normal worker count number to a single one, and still seems to take almost 100M more every day!

**Comment by vstakhov** [comment]
I don't observe such a behaviour anywhere. Can you reproduce it with the master branch?

**Comment by athanp** [comment]
I will give it a try and keep you informed

**Comment by athanp** [comment]
Problem persists. Three hours ago started at 234M and now is 310M Same as 1.4.1 and 1.4.2.
Even tried the precompiled freebsd package from latest repository (1.4.2) with default config that comes with!
Tests run on a C2750 server, an i7 setup, and a Xeon dedicated.

PS, I'm trying not to use any custom setup to help you track this issue

**Comment by RvdE** [comment]
I'm seeing the same on my FreeBSD 11 amd64 machine running 1.4.2. Need to restart rspamd every other day to avoid running out of memory. Also using redis and mostly basic setup.

**Comment by vstakhov** [comment]
Erm, can anybody test the master branch instead of 1.4?

**Comment by RalfvdEnden** [comment]
I've updated mail/rspamd-devel on my box to grab 1c31d90 from github and also updated the LIB_DEPENDS and CMAKE_ARGS to the ones from mail/rspamd. All the rspamd processes are taking up around 245M. Will have to wait and see how it behaves over time. To be continued...

**Comment by RalfvdEnden** [comment]
I'm not seeing the same behaviour with master as 1.4.2.

Memory consumption is more predictable and it doesn't exhaust my memory anymore. Good job.

**Comment by athanp** [comment]
Master definitely works better than 1.4.2
I'm running it five days now and normal worker ram usage has never exceed 350M.
Still grows from 230M when first started though not as bad as 1.4.2

**Comment by fatalbanana** [comment]
@athanp do you use reload?

**Comment by athanp** [comment]
@fatalbanana I'm using 1.4.3 since yesterday. Normal worker clean started at 231mb and twelve hours and 4-5 scanned email later is 337mb and still grows. Same setup as always using mostly defaults (FreeBSD 11p7 x64)

ps: What you mean by "reload"?

**Comment by damned-trooper** [comment]
Hi, some statistic from CentOS 7 (last updates) with yesterday rspamd build from master branch:
Yesterday
13:52:
 2709 _rspamd   20   0  385632  43516   2688 S   0.0  2.3   0:34.78 rspamd
 2710 _rspamd   20   0  404800  44824   3188 S   0.0  2.4   0:23.76 rspamd
 2712 _rspamd   20   0  497824 149496  17368 S   0.0  8.0   0:48.85 rspamd
 2713 _rspamd   20   0  485436 139780  17788 S   0.0  7.5   0:50.08 rspamd

15:12:
 2709 _rspamd   20   0  388668  46224   2688 S   0.0  2.5   0:38.07 rspamd
 2710 _rspamd   20   0  407836  47788   3196 S   0.0  2.5   0:26.01 rspamd
 2712 _rspamd   20   0  497824 150688  18560 S   0.0  8.0   0:53.52 rspamd
 2713 _rspamd   20   0  490480 145612  18488 S   0.0  7.8   0:54.71 rspamd

22:08:
 2709 _rspamd   20   0  403868  61160   2676 S   0.0  3.3   0:54.78 rspamd
 2710 _rspamd   20   0  422928  62404   3136 S   0.0  3.3   0:37.46 rspamd
 2712 _rspamd   20   0  509084 160896  17936 S   0.0  8.6   1:16.13 rspamd
 2713 _rspamd   20   0  503972 158188  17948 S   0.0  8.4   1:17.46 rspamd

Today:
1:01:
 2709 _rspamd   20   0  410220  65516   2676 S   0.0  3.5   1:01.84 rspamd
 2710 _rspamd   20   0  429412  67876   3136 S   0.0  3.6   0:42.26 rspamd
 2712 _rspamd   20   0  516260 167636  17932 S   0.0  8.9   1:25.47 rspamd
 2713 _rspamd   20   0  520224 173556  17968 S   0.0  9.3   1:28.06 rspamd

10:11:
 2709 _rspamd   20   0  430560  85628   2676 S   0.0  4.6   1:24.10 rspamd
 2710 _rspamd   20   0  449500  87968   3172 S   0.3  4.7   0:57.59 rspamd
 2712 _rspamd   20   0  532948 185416  18588 S   0.0  9.9   1:55.66 rspamd
 2713 _rspamd   20   0  532840 187200  18840 S   0.0 10.0   1:58.79 rspamd

10:50:
 2709 _rspamd   20   0  432012  87192   2676 S   0.0  4.6   1:25.70 rspamd
 2710 _rspamd   20   0  450952  89444   3168 S   0.0  4.8   0:58.72 rspamd
 2712 _rspamd   20   0  532948 185512  18688 S   0.7  9.9   1:58.36 rspamd
 2713 _rspamd   20   0  532840 187204  18848 S   0.0 10.0   2:01.18 rspamd

Looks like memory leak exists.

**Comment by vstakhov** [comment]
It doesn't show anything and is basically useless to find memory leaks. In the default configuration there are no leaks, therefore, I suppose you have something in your configuration that causes leak. Do you see any errors in your logs?

**Comment by damned-trooper** [comment]
Yes. I understand it, but i have no ideas, how to troubleshout this problem.

Last errors in rspamd log:

> Jan 26 04:52:03 mx01 rspamd[2713]: <e0782a>; lua; once_received.lua:35: error looking up 2.17.156.207.in-addr.arpa: server fail
> Jan 26 05:20:28 mx01 rspamd[2712]: <cae947>; lua; hfilter.lua:147: error looking up gsec.se: server fail
> Jan 26 05:31:10 mx01 rspamd[2713]: <c57d3c>; lua; ratelimit.lua:326: got error while setting limit: timeout while connecting the server
> Jan 26 05:31:10 mx01 rspamd[2713]: <c57d3c>; lua; ip_score.lua:108: got error while IP score changing: timeout while connecting the server
> Jan 26 06:55:43 mx01 rspamd[2713]: <395910>; lua; ratelimit.lua:326: got error while setting limit: timeout while connecting the server
> Jan 26 06:55:43 mx01 rspamd[2713]: <395910>; lua; ip_score.lua:108: got error while IP score changing: timeout while connecting the server
> Jan 26 07:47:50 mx01 rspamd[2712]: <506d3f>; lua; hfilter.lua:147: error looking up 4003004.ru: server fail
> Jan 26 08:49:23 mx01 rspamd[2713]: <40ae89>; lua; once_received.lua:35: error looking up 34.154.113.42.in-addr.arpa: server fail
> Jan 26 08:49:28 mx01 rspamd[2712]: <a22d53>; lua; once_received.lua:35: error looking up 34.154.113.42.in-addr.arpa: server fail
> Jan 26 10:41:06 mx01 rspamd[2713]: <907b47>; lua; once_received.lua:35: error looking up 204.85.194.120.in-addr.arpa: server fail
> Jan 26 11:46:24 mx01 rspamd[2713]: <defe0a>; spf; parse_spf_record: <CAGmDdMk9qWZ3ev-cUWNGjVN=F3p8G4J4__M9BEC8qnq3xFQaQg@mail.gmail.com>: spf error for domain it-cable.ru: bad spf command ,
> Jan 26 12:39:50 mx01 rspamd[55245]: <cwadkf>; map; http_map_finish: cannot load map http://rspamd.com/update/rspamd-1.5.ucl from rspamd.com: HTTP error 404
> Jan 26 13:20:44 mx01 rspamd[55245]: <381988>; lua; hfilter.lua:147: error looking up smtp.btrust360.com: server fail

Nothing helpful.

After service restart there is nothing wrong in logs.

**Comment by mnik247** [comment]
I can confirm problem with mem leak  for v1.4.x too.
About two weeks ago I upgrade rspamd from v1.3.5 to v1.4.1 and then to v1.4.2 from offical repo Centos 6.
v1.4.3 not published yet in repo for Centos 6.
I must reboot rspamd every 3-5 days....
![rspamd-20170126](https://cloud.githubusercontent.com/assets/14947247/22329891/11869bb6-e3cc-11e6-8b9d-8a313756c6da.jpg)

**Comment by vstakhov** [comment]
Well, that all doesn't help at all. The only way to find a memory leak is to run valgrind:

```
VALGRIND=1 G_SLICE=always-malloc sudo -E valgrind --log-file=rspamd-%p.log --trace-children=yes --malloc-fill=0xde --free-fill=0xed  rspamd -u _rspamd -g _rspamd -c /etc/rspamd/rspamd.conf -f
```

However, it requires that your traffic is not so high as valgrind significantly slows down Rspamd (more than 10 times) and (what's more problematic) your Rspamd is **NOT** build with luajit. By default Rspamd is built with luajit...

**Comment by vstakhov** [comment]
JFYI, I constantly run valgrind so there are no leaks in the default configuration.

**Comment by damned-trooper** [comment]
I'll try to use Valgrind tomorrow. Today i have a lot of pain with our M$ SharePoint, so there is no time.
Sorry.

**Comment by vstakhov** [comment]
No worries. I personally suppose this leak might be related to timeouts or other errors handling.

**Comment by damned-trooper** [comment]
I'm sorry for stupid question. Is it enough to change `OPTION(ENABLE_LUAJIT` to `OFF` in CMakeLists.txt and rebuild rspamd to turn off luajit?

**Comment by csmk** [comment]
You should use `-DENABLE_LUAJIT=OFF` during the configure phase.

**Comment by damned-trooper** [comment]
From log:

> ==13394== Rerun with --leak-check=full to see details of leaked memory
> ==13394==
> ==13394== For counts of detected and suppressed errors, rerun with: -v
> ==13394== Use --track-origins=yes to see where uninitialised values come from

Shall i add this options and rerun valgrind?

**Comment by damned-trooper** [comment]
==13518== Memcheck, a memory error detector
==13518== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==13518== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==13518== Command: rspamd -u _rspamd -g _rspamd -c /etc/rspamd/rspamd.conf -f
==13518== Parent PID: 13517
==13518==
==13518== Conditional jump or move depends on uninitialised value(s)
==13518==    at 0x46A50E: rspamd_strlcpy (str_util.c:344)
==13518==    by 0x47567B: lua_logger_log_format.isra.1.constprop.2 (lua_logger.c:598)
==13518==    by 0x475A0C: lua_logger_logx (lua_logger.c:672)
==13518==    by 0x76AB323: ??? (in /usr/lib64/liblua-5.1.so)
==13518==    by 0x76B5E56: ??? (in /usr/lib64/liblua-5.1.so)
==13518==    by 0x76AB74C: ??? (in /usr/lib64/liblua-5.1.so)
==13518==    by 0x76AAA6D: ??? (in /usr/lib64/liblua-5.1.so)
==13518==    by 0x76AB8D9: ??? (in /usr/lib64/liblua-5.1.so)
==13518==    by 0x76A744C: lua_pcall (in /usr/lib64/liblua-5.1.so)
==13518==    by 0x473121: rspamd_init_lua_filters (lua_common.c:380)
==13518==    by 0x498F0F: rspamd_init_filters (cfg_utils.c:1370)
==13518==    by 0x434020: load_rspamd_config (rspamd.c:857)
==13518==
==13518== Conditional jump or move depends on uninitialised value(s)
==13518==    at 0x46A50E: rspamd_strlcpy (str_util.c:344)
==13518==    by 0x4751E4: UnknownInlinedFun (lua_logger.c:376)
==13518==    by 0x4751E4: lua_logger_out_type (lua_logger.c:435)
==13518==    by 0x47567B: lua_logger_log_format.isra.1.constprop.2 (lua_logger.c:598)
==13518==    by 0x475A0C: lua_logger_logx (lua_logger.c:672)
==13518==    by 0x76AB323: ??? (in /usr/lib64/liblua-5.1.so)
==13518==    by 0x76B5E56: ??? (in /usr/lib64/liblua-5.1.so)
==13518==    by 0x76AB74C: ??? (in /usr/lib64/liblua-5.1.so)
==13518==    by 0x76AAA6D: ??? (in /usr/lib64/liblua-5.1.so)
==13518==    by 0x76AB8D9: ??? (in /usr/lib64/liblua-5.1.so)
==13518==    by 0x76A744C: lua_pcall (in /usr/lib64/liblua-5.1.so)
==13518==    by 0x473121: rspamd_init_lua_filters (lua_common.c:380)
==13518==    by 0x498F0F: rspamd_init_filters (cfg_utils.c:1370)
==13518==
==13518== Conditional jump or move depends on uninitialised value(s)
==13518==    at 0x46A50E: rspamd_strlcpy (str_util.c:344)
==13518==    by 0x4B0D7D: rspamd_roll_history_load (roll_history.c:250)
==13518==    by 0x4271CF: main (rspamd.c:1340)
==13518==
==13518== Conditional jump or move depends on uninitialised value(s)
==13518==    at 0x46A50E: rspamd_strlcpy (str_util.c:344)
==13518==    by 0x4B0EC0: rspamd_roll_history_load (roll_history.c:271)
==13518==    by 0x4271CF: main (rspamd.c:1340)
==13518==
==13518== Conditional jump or move depends on uninitialised value(s)
==13518==    at 0x46A50E: rspamd_strlcpy (str_util.c:344)
==13518==    by 0x4B0F20: rspamd_roll_history_load (roll_history.c:257)
==13518==    by 0x4271CF: main (rspamd.c:1340)
==13518==
==13518==
==13518== HEAP SUMMARY:
==13518==     in use at exit: 6,592,349 bytes in 65,195 blocks
==13518==   total heap usage: 134,532 allocs, 69,337 frees, 25,993,069 bytes allocated
==13518==
==13518== 62 (24 direct, 38 indirect) bytes in 1 blocks are definitely lost in loss record 3,277 of 6,331
==13518==    at 0x4C27BE3: malloc (vg_replace_malloc.c:299)
==13518==    by 0x509830D: g_malloc (in /usr/lib64/libglib-2.0.so.0.4600.2)
==13518==    by 0x50B1322: g_strsplit_set (in /usr/lib64/libglib-2.0.so.0.4600.2)
==13518==    by 0x450E93: rspamd_parse_unix_path (addr.c:321)
==13518==    by 0x45201A: rspamd_parse_inet_address (addr.c:594)
==13518==    by 0x427180: main (rspamd.c:1322)
==13518==
==13518== 144 bytes in 6 blocks are definitely lost in loss record 5,163 of 6,331
==13518==    at 0x4C27BE3: malloc (vg_replace_malloc.c:299)
==13518==    by 0x509830D: g_malloc (in /usr/lib64/libglib-2.0.so.0.4600.2)
==13518==    by 0x50AE0FD: g_slice_alloc (in /usr/lib64/libglib-2.0.so.0.4600.2)
==13518==    by 0x50AE63D: g_slice_alloc0 (in /usr/lib64/libglib-2.0.so.0.4600.2)
==13518==    by 0x498DF6: rspamd_init_filters (cfg_utils.c:1330)
==13518==    by 0x434020: load_rspamd_config (rspamd.c:857)
==13518==    by 0x426F78: main (rspamd.c:1245)
==13518==
==13518== 1,089 (128 direct, 961 indirect) bytes in 2 blocks are definitely lost in loss record 5,927 of 6,331
==13518==    at 0x4C27BE3: malloc (vg_replace_malloc.c:299)
==13518==    by 0x523E47: ucl_object_new_full (ucl_util.c:2620)
==13518==    by 0x523F54: ucl_object_fromstring_common (ucl_util.c:1998)
==13518==    by 0x526620: ucl_save_comment.isra.8.part.9 (ucl_parser.c:98)
==13518==    by 0x526EF0: ucl_save_comment (ucl_parser.c:153)
==13518==    by 0x526EF0: ucl_skip_comments (ucl_parser.c:149)
==13518==    by 0x52B089: ucl_parse_key (ucl_parser.c:1210)
==13518==    by 0x52B089: ucl_state_machine (ucl_parser.c:2230)
==13518==    by 0x52B089: ucl_parser_add_chunk_full (ucl_parser.c:2648)
==13518==    by 0x524834: ucl_include_file_single (ucl_util.c:1174)
==13518==    by 0x525198: ucl_include_file.part.7 (ucl_util.c:1276)
==13518==    by 0x52578E: ucl_include_common (ucl_util.c:1406)
==13518==    by 0x52ADBD: ucl_state_machine (ucl_parser.c:2386)
==13518==    by 0x52ADBD: ucl_parser_add_chunk_full (ucl_parser.c:2648)
==13518==    by 0x524834: ucl_include_file_single (ucl_util.c:1174)
==13518==    by 0x52578E: ucl_include_common (ucl_util.c:1406)
==13518==
==13518== 2,358 (216 direct, 2,142 indirect) bytes in 1 blocks are definitely lost in loss record 6,085 of 6,331
==13518==    at 0x4C27BE3: malloc (vg_replace_malloc.c:299)
==13518==    by 0x509830D: g_malloc (in /usr/lib64/libglib-2.0.so.0.4600.2)
==13518==    by 0x46EFF8: init_title (util.c:858)
==13518==    by 0x426ADA: main (rspamd.c:1134)
==13518==
==13518== LEAK SUMMARY:
==13518==    definitely lost: 512 bytes in 10 blocks
==13518==    indirectly lost: 3,141 bytes in 48 blocks
==13518==      possibly lost: 0 bytes in 0 blocks
==13518==    still reachable: 6,588,696 bytes in 65,137 blocks
==13518==         suppressed: 0 bytes in 0 blocks
==13518== Reachable blocks (those to which a pointer was found) are not shown.
==13518== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==13518==
==13518== For counts of detected and suppressed errors, rerun with: -v
==13518== ERROR SUMMARY: 457 errors from 9 contexts (suppressed: 0 from 0)

**Comment by damned-trooper** [comment]
Detailed information:
[rspamd-13591.txt](https://github.com/vstakhov/rspamd/files/734809/rspamd-13591.txt)

**Comment by vstakhov** [comment]
It seems you've forgotten to trace Rspamd children. Here is the corrected command:

```
VALGRIND=1 G_SLICE=always-malloc sudo -E valgrind --log-file=rspamd-%p.log --trace-children=yes --leak-check=full --malloc-fill=0xde --free-fill=0xed  rspamd -u _rspamd -g _rspamd -c /etc/rspamd/rspamd.conf -f
```

If you build Rspamd with jemalloc then it is required to disable it as well.

**Comment by damned-trooper** [comment]
Jemalloc disabled:
`OPTION(ENABLE_JEMALLOC     "Build rspamd with jemalloc allocator  [default: OFF]" OFF)`

Valgrind result:

```
==15153== Memcheck, a memory error detector
==15153== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==15153== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==15153== Command: rspamd -u _rspamd -g _rspamd -c /etc/rspamd/rspamd.conf -f
==15153== Parent PID: 15152
==15153==
==15153== Conditional jump or move depends on uninitialised value(s)
==15153==    at 0x46A50E: rspamd_strlcpy (str_util.c:344)
==15153==    by 0x47567B: lua_logger_log_format.isra.1.constprop.2 (lua_logger.c:598)
==15153==    by 0x475A0C: lua_logger_logx (lua_logger.c:672)
==15153==    by 0x76AB323: ??? (in /usr/lib64/liblua-5.1.so)
==15153==    by 0x76B5E56: ??? (in /usr/lib64/liblua-5.1.so)
==15153==    by 0x76AB74C: ??? (in /usr/lib64/liblua-5.1.so)
==15153==    by 0x76AAA6D: ??? (in /usr/lib64/liblua-5.1.so)
==15153==    by 0x76AB8D9: ??? (in /usr/lib64/liblua-5.1.so)
==15153==    by 0x76A744C: lua_pcall (in /usr/lib64/liblua-5.1.so)
==15153==    by 0x473121: rspamd_init_lua_filters (lua_common.c:380)
==15153==    by 0x498F0F: rspamd_init_filters (cfg_utils.c:1370)
==15153==    by 0x434020: load_rspamd_config (rspamd.c:857)
==15153==
==15153== Conditional jump or move depends on uninitialised value(s)
==15153==    at 0x46A50E: rspamd_strlcpy (str_util.c:344)
==15153==    by 0x4751E4: UnknownInlinedFun (lua_logger.c:376)
==15153==    by 0x4751E4: lua_logger_out_type (lua_logger.c:435)
==15153==    by 0x47567B: lua_logger_log_format.isra.1.constprop.2 (lua_logger.c:598)
==15153==    by 0x475A0C: lua_logger_logx (lua_logger.c:672)
==15153==    by 0x76AB323: ??? (in /usr/lib64/liblua-5.1.so)
==15153==    by 0x76B5E56: ??? (in /usr/lib64/liblua-5.1.so)
==15153==    by 0x76AB74C: ??? (in /usr/lib64/liblua-5.1.so)
==15153==    by 0x76AAA6D: ??? (in /usr/lib64/liblua-5.1.so)
==15153==    by 0x76AB8D9: ??? (in /usr/lib64/liblua-5.1.so)
==15153==    by 0x76A744C: lua_pcall (in /usr/lib64/liblua-5.1.so)
==15153==    by 0x473121: rspamd_init_lua_filters (lua_common.c:380)
==15153==    by 0x498F0F: rspamd_init_filters (cfg_utils.c:1370)
==15153==
==15153== Conditional jump or move depends on uninitialised value(s)
==15153==    at 0x46A50E: rspamd_strlcpy (str_util.c:344)
==15153==    by 0x4B0D7D: rspamd_roll_history_load (roll_history.c:250)
==15153==    by 0x4271CF: main (rspamd.c:1340)
==15153==
==15153== Conditional jump or move depends on uninitialised value(s)
==15153==    at 0x46A50E: rspamd_strlcpy (str_util.c:344)
==15153==    by 0x4B0EC0: rspamd_roll_history_load (roll_history.c:271)
==15153==    by 0x4271CF: main (rspamd.c:1340)
==15153==
==15153== Conditional jump or move depends on uninitialised value(s)
==15153==    at 0x46A50E: rspamd_strlcpy (str_util.c:344)
==15153==    by 0x4B0F20: rspamd_roll_history_load (roll_history.c:257)
==15153==    by 0x4271CF: main (rspamd.c:1340)
==15153==
==15153==
==15153== HEAP SUMMARY:
==15153==     in use at exit: 6,592,329 bytes in 65,195 blocks
==15153==   total heap usage: 134,532 allocs, 69,337 frees, 25,993,049 bytes allocated
==15153==
==15153== 62 (24 direct, 38 indirect) bytes in 1 blocks are definitely lost in loss record 3,277 of 6,331
==15153==    at 0x4C27BE3: malloc (vg_replace_malloc.c:299)
==15153==    by 0x509830D: g_malloc (in /usr/lib64/libglib-2.0.so.0.4600.2)
==15153==    by 0x50B1322: g_strsplit_set (in /usr/lib64/libglib-2.0.so.0.4600.2)
==15153==    by 0x450E93: rspamd_parse_unix_path (addr.c:321)
==15153==    by 0x45201A: rspamd_parse_inet_address (addr.c:594)
==15153==    by 0x427180: main (rspamd.c:1322)
==15153==
==15153== 144 bytes in 6 blocks are definitely lost in loss record 5,163 of 6,331
==15153==    at 0x4C27BE3: malloc (vg_replace_malloc.c:299)
==15153==    by 0x509830D: g_malloc (in /usr/lib64/libglib-2.0.so.0.4600.2)
==15153==    by 0x50AE0FD: g_slice_alloc (in /usr/lib64/libglib-2.0.so.0.4600.2)
==15153==    by 0x50AE63D: g_slice_alloc0 (in /usr/lib64/libglib-2.0.so.0.4600.2)
==15153==    by 0x498DF6: rspamd_init_filters (cfg_utils.c:1330)
==15153==    by 0x434020: load_rspamd_config (rspamd.c:857)
==15153==    by 0x426F78: main (rspamd.c:1245)
==15153==
==15153== 1,089 (128 direct, 961 indirect) bytes in 2 blocks are definitely lost in loss record 5,927 of 6,331
==15153==    at 0x4C27BE3: malloc (vg_replace_malloc.c:299)
==15153==    by 0x523E47: ucl_object_new_full (ucl_util.c:2620)
==15153==    by 0x523F54: ucl_object_fromstring_common (ucl_util.c:1998)
==15153==    by 0x526620: ucl_save_comment.isra.8.part.9 (ucl_parser.c:98)
==15153==    by 0x526EF0: ucl_save_comment (ucl_parser.c:153)
==15153==    by 0x526EF0: ucl_skip_comments (ucl_parser.c:149)
==15153==    by 0x52B089: ucl_parse_key (ucl_parser.c:1210)
==15153==    by 0x52B089: ucl_state_machine (ucl_parser.c:2230)
==15153==    by 0x52B089: ucl_parser_add_chunk_full (ucl_parser.c:2648)
==15153==    by 0x524834: ucl_include_file_single (ucl_util.c:1174)
==15153==    by 0x525198: ucl_include_file.part.7 (ucl_util.c:1276)
==15153==    by 0x52578E: ucl_include_common (ucl_util.c:1406)
==15153==    by 0x52ADBD: ucl_state_machine (ucl_parser.c:2386)
==15153==    by 0x52ADBD: ucl_parser_add_chunk_full (ucl_parser.c:2648)
==15153==    by 0x524834: ucl_include_file_single (ucl_util.c:1174)
==15153==    by 0x52578E: ucl_include_common (ucl_util.c:1406)
==15153==
==15153== 2,338 (216 direct, 2,122 indirect) bytes in 1 blocks are definitely lost in loss record 6,085 of 6,331
==15153==    at 0x4C27BE3: malloc (vg_replace_malloc.c:299)
==15153==    by 0x509830D: g_malloc (in /usr/lib64/libglib-2.0.so.0.4600.2)
==15153==    by 0x46EFF8: init_title (util.c:858)
==15153==    by 0x426ADA: main (rspamd.c:1134)
==15153==
==15153== LEAK SUMMARY:
==15153==    definitely lost: 512 bytes in 10 blocks
==15153==    indirectly lost: 3,121 bytes in 48 blocks
==15153==      possibly lost: 0 bytes in 0 blocks
==15153==    still reachable: 6,588,696 bytes in 65,137 blocks
==15153==         suppressed: 0 bytes in 0 blocks
==15153== Reachable blocks (those to which a pointer was found) are not shown.
==15153== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==15153==
==15153== For counts of detected and suppressed errors, rerun with: -v
==15153== Use --track-origins=yes to see where uninitialised values come from
==15153== ERROR SUMMARY: 457 errors from 9 contexts (suppressed: 0 from 0)
 
```

**Comment by vstakhov** [comment]
You should wait and scan some messages. According to your traces, Rspamd hasn't even started... You might need to wait for a long time with valgrind to even start Rspamd (about couple of minutes). Thereafter, you need to do some tasks that normally cause memory leaking and wait again (about 30-40 minutes).

**Comment by damned-trooper** [comment]
Oops... I have fail with Valgrind. Now i ran it in correct manner, and will wait for some actual details. Thanks a lot.
I'll send results later.

**Comment by damned-trooper** [comment]
New log here:
[rspamd-15556.txt](https://github.com/vstakhov/rspamd/files/735175/rspamd-15556.txt)

**Comment by vstakhov** [comment]
Thank you very much for your report. It seems that the leak is in the maps processing code. I will check it later.

**Comment by vstakhov** [comment]
Do you see any maps related errors btw?

**Comment by damned-trooper** [comment]
Only this errors:
```
Jan 27 13:51:12 mx01 rspamd[15153]: <9fe600>; main; rspamd_hard_terminate: shutting down Rspamd due to fatal error
Jan 27 14:06:34 mx01 rspamd[13317]: <52d67f>; spf; parse_spf_record: <VI1PR0401MB1886F062DCF8ABFACBAA3BD6BA760@VI1PR0401MB1886.eurprd04.prod.outlook.com>: spf error for domain on-channel.com: bad spf command 148.105.12.0/24
Jan 27 14:08:16 mx01 rspamd[15501]: <cwadkf>; map; http_map_finish: cannot load map http://rspamd.com/update/rspamd-1.5.ucl from rspamd.com: HTTP error 404
Jan 27 14:08:19 mx01 rspamd[15492]: <1474eb>; main; rspamd_hard_terminate: kill worker 0000000000003C95 as Rspamd is terminating due to an unrecoverable error
Jan 27 14:08:19 mx01 rspamd[15492]: <1474eb>; main; rspamd_hard_terminate: shutting down Rspamd due to fatal error
Jan 27 14:10:42 mx01 rspamd[15559]: <cwadkf>; map; http_map_finish: cannot load map http://rspamd.com/update/rspamd-1.5.ucl from rspamd.com: HTTP error 404
Jan 27 14:18:04 mx01 rspamd[15561]: <9ownwh>; monitored; rspamd_monitored_propagate_error: invalid return on resolving multi.uribl.com, disable object
Jan 27 14:18:14 mx01 rspamd[15562]: <9ownwh>; monitored; rspamd_monitored_propagate_error: invalid return on resolving multi.uribl.com, disable object
Jan 27 15:04:55 mx01 rspamd[16553]: <cwadkf>; map; http_map_finish: cannot load map http://rspamd.com/update/rspamd-1.5.ucl from rspamd.com: HTTP error 404
Jan 27 15:09:56 mx01 rspamd[16556]: <9ownwh>; monitored; rspamd_monitored_propagate_error: invalid return on resolving multi.uribl.com, disable object
Jan 27 15:10:15 mx01 rspamd[16555]: <9ownwh>; monitored; rspamd_monitored_propagate_error: invalid return on resolving multi.uribl.com, disable object
Jan 27 15:16:27 mx01 rspamd[16556]: <63a613>; spf; parse_spf_record: <VI1PR0401MB1886B2677FB1B5BB2C34DEC0BA760@VI1PR0401MB1886.eurprd04.prod.outlook.com>: spf error for domain on-channel.com: bad spf command 148.105.12.0/24
Jan 27 15:16:27 mx01 rspamd[16556]: <4d0563>; spf; parse_spf_record: <VI1PR0401MB1886B2677FB1B5BB2C34DEC0BA760@VI1PR0401MB1886.eurprd04.prod.outlook.com>: spf error for domain on-channel.com: bad spf command 148.105.12.0/24
Jan 27 15:25:29 mx01 rspamd[16556]: <9ownwh>; monitored; rspamd_monitored_propagate_error: invalid return on resolving multi.uribl.com, disable object
Jan 27 16:38:21 mx01 rspamd[16555]: <9ownwh>; monitored; rspamd_monitored_propagate_error: invalid return on resolving multi.uribl.com, disable object

```

Map error only with  `http://rspamd.com/update/rspamd-1.5.ucl`

**Comment by damned-trooper** [comment]
14:08 terminate - it's my experiments.

**Comment by vstakhov** [comment]
It also seems that you are using an outdated Rspamd version for your tests...

**Comment by vstakhov** [comment]
Or wait...

**Comment by damned-trooper** [comment]
I build this package today right before tests. It was last version from git (master branch).

**Comment by vstakhov** [comment]
Well, I've found one leak. SSL leak looks very strange. I've reproduced it but I have completely no idea if it consumes memory constantly or just capped at some limit. Could you please try an updated version and take a look at memory consumption (presumably without valgrind but for a long time).

**Comment by damned-trooper** [comment]
I've build new package from master.
Tomorrow i'll send you statistics about memory consumption.

**Comment by damned-trooper** [comment]
Looks like problem still exists:

22978 _rspamd   20   0  548500 196512  17672 S   0.0 10.5   1:58.74 rspamd
22979 _rspamd   20   0  550072 196060  17768 S   0.0 10.5   2:00.86 rspamd
22977 _rspamd   20   0  468832 103252   3000 S   0.0  5.5   1:09.64 rspamd
22976 _rspamd   20   0  448736  92176   2604 S   0.0  4.9   1:40.21 rspamd


Do you need another Valgrind report?

**Comment by vstakhov** [comment]
I still observe the OpenSSL leak:

~~~
==25061== 1,830,166 (97,088 direct, 1,733,078 indirect) bytes in 296 blocks are definitely lost in loss record 642 of 642
==25061==    at 0x4C2ABAF: malloc (vg_replace_malloc.c:299)
==25061==    by 0x62836DD: CRYPTO_zalloc (mem.c:100)
==25061==    by 0x61BE7E6: asn1_item_embed_new (tasn_new.c:122)
==25061==    by 0x61BC7B3: asn1_item_embed_d2i (tasn_dec.c:290)
==25061==    by 0x61BCE3A: ASN1_item_ex_d2i (tasn_dec.c:114)
==25061==    by 0x61BCEBA: ASN1_item_d2i (tasn_dec.c:104)
==25061==    by 0x5EE8623: tls_process_server_certificate (statem_clnt.c:1207)
==25061==    by 0x5EE5F1E: read_state_machine (statem.c:589)
==25061==    by 0x5EE5F1E: state_machine (statem.c:385)
==25061==    by 0x5EDE6D0: SSL_do_handshake (ssl_lib.c:3025)
==25061==    by 0x1DA7C4: rspamd_ssl_event_handler (ssl_util.c:356)
==25061==    by 0x55CF59F: event_process_active_single_queue (event.c:1350)
==25061==    by 0x55CF59F: event_process_active (event.c:1420)
==25061==    by 0x55CF59F: event_base_loop (event.c:1621)
==25061==    by 0x171534: start_worker (worker.c:636)
==25061==    by 0x240CCB: rspamd_fork_worker (worker_util.c:607)
==25061==    by 0x16D944: spawn_worker_type (rspamd.c:521)
==25061==    by 0x16DBE1: spawn_workers (rspamd.c:594)
==25061==    by 0x16FD85: main (rspamd.c:1376)
~~~

**Comment by vstakhov** [comment]
It seems that I've found the issue: `SSL_get_peer_certificate` used during certificate validation increases refcount by one for the `SSL` structure. Hence, resources are leaking here.

**Comment by vstakhov** [comment]
Ok, I have fixed this leak most likely and I have backported it to the 1.4 branch. Thank you for your collaboration!

**Comment by damned-trooper** [comment]
As i can see, today memory consumption of rspamd looks better:

```
63864 _rspamd   20   0  466824 105052  19788 S   0.0  5.6   0:42.33 rspamd
63865 _rspamd   20   0  467588  74464  19680 S   0.0  4.0   0:43.49 rspamd
63863 _rspamd   20   0  376772  15372   3908 S   0.0  0.8   0:34.22 rspamd
63862 _rspamd   20   0  357476  13880   3188 S   0.0  0.7   0:18.25 rspamd
63861 root      20   0  353852  12424   5124 S   0.0  0.7   0:00.14 rspamd
```

(new packahe was build and installed yesterday evening (`   Active: active (running) since Sun 2017-01-29 21:11:51 MSK; 13h ago`)

I will monitoring memory consumption for a few days, but it's really looks like, that there is no more problems.

**Comment by damned-trooper** [comment]
I'm in doubt...

```
30.01.17 18:28:

63864 _rspamd   20   0  490832 129920  20700 S   0.3  6.9   1:17.86 rspamd
63865 _rspamd   20   0  471592 123112  20740 S   0.0  6.6   1:16.72 rspamd
63863 _rspamd   20   0  377040  15420   3936 S   0.3  0.8   0:59.52 rspamd
63862 _rspamd   20   0  357680  13884   3188 S   0.0  0.7   0:34.54 rspamd
63861 root      20   0  353852  12424   5124 S   0.0  0.7   0:00.14 rspamd

31.01.17 11:44:
63864 _rspamd   20   0  490236 144604  19520 S   0.3  7.7   2:46.51 rspamd
63865 _rspamd   20   0  471592 136340  19632 S   0.0  7.3   2:29.17 rspamd
63863 _rspamd   20   0  377040  14716   3232 S   0.0  0.8   2:04.20 rspamd
63862 _rspamd   20   0  357680  13372   2676 S   0.0  0.7   1:24.43 rspamd
63861 root      20   0  353852  11284   3984 S   0.0  0.6   0:00.14 rspamd

01.02.17 12:53:
63865 _rspamd   20   0  502948 164092  19400 S   0.0  8.7   4:13.77 rspamd
63864 _rspamd   20   0  503348 157544  19060 S   0.0  8.4   4:54.54 rspamd
63863 _rspamd   20   0  377040  10500   3296 S   0.3  0.6   3:38.22 rspamd
63862 _rspamd   20   0  357680   7524   2764 S   0.0  0.4   2:36.76 rspamd
63861 root      20   0  353852   6128   3984 S   0.0  0.3   0:00.14 rspamd
```

Is this normal situation or a little memory leak still exists?

**Comment by damned-trooper** [comment]
Two hours interval today:
```
01.02.17 11:02:
63865 _rspamd   20   0  502948 163540  18856 S   0.0  8.7   4:05.94 rspamd
63864 _rspamd   20   0  505408 156704  18236 S   0.3  8.4   4:44.57 rspamd
63863 _rspamd   20   0  377040  10492   3288 S   0.0  0.6   3:31.30 rspamd
63862 _rspamd   20   0  357680   7524   2764 S   0.0  0.4   2:31.47 rspamd
63861 root      20   0  353852   6128   3984 S   0.0  0.3   0:00.14 rspamd

01.02.17 12:53:
63865 _rspamd   20   0  502948 164092  19400 S   0.0  8.7   4:13.77 rspamd
63864 _rspamd   20   0  503348 157544  19060 S   0.0  8.4   4:54.54 rspamd
63863 _rspamd   20   0  377040  10500   3296 S   0.3  0.6   3:38.22 rspamd
63862 _rspamd   20   0  357680   7524   2764 S   0.0  0.4   2:36.76 rspamd
63861 root      20   0  353852   6128   3984 S   0.0  0.3   0:00.14 rspamd
```
It's very small grow of RES (500 kib per hour), but it exists.

**Comment by damned-trooper** [comment]
So, looks like it's not a leak...
Today 18:33
```
63865 _rspamd   20   0  502948 163712  19024 S   0.0  8.7   4:40.69 rspamd
63864 _rspamd   20   0  503348 157452  18952 S   0.3  8.4   5:25.77 rspamd
63863 _rspamd   20   0  377040  10392   3192 S   0.0  0.6   4:02.07 rspamd
63862 _rspamd   20   0  357680   7444   2684 S   0.0  0.4   2:54.01 rspamd
```
PID 63865 RES reduced.
Excuse me for panic.

**Comment by setiseta** [comment]
Hello,
I think there is one, but don't know where to start.
I restarted rspamed today for about 5 hours.
It startet with 4.2GB Ram usage (1 controller process and 8 'normal process')

and no 5 hours later im on 7.4GB for the same count of processes.
the rspamd webfrontend tells me that there were 470 mails.
think that is not too much.

any hints where to start analyzing?
could it be the same as fixed here?
there is no release of this fix or am i wrong?

Thx for help

**Comment by vstakhov** [comment]
What version do you use?

**Comment by setiseta** [comment]
rspamed version: 1.4.3

**Comment by vstakhov** [comment]
There is no stable release with memory leak fixed. You can either update to `rspamd-1.4` branch or migrate to experimental packages.

**Comment by vstakhov** [comment]
Fixed in 1.4.4.

**Comment by towerplease** [comment]
Running on a very small VPS -> 1 Vcore and 256 MB RAM.

rspamd.log:
2018-01-17 13:01:44 #1864(main) <e7cd9c>; main; rspamd_fork_worker: cannot fork main process. Cannot allocate memory
2018-01-17 13:01:44 #1864(main) <e7cd9c>; main; rspamd_hard_terminate: shutting down Rspamd due to fatal error

Cant see any missconfiguration or anything. I have 140 of 240 MB RAM used atm (Result from htop)

Does rspamd need more RAM or any other Problem possible?

Thank you!!

**Comment by setiseta** [comment]
i think 140mb free ram is a bit low.
my rspamd docker uses ~750mb ram.
