### ISSUE TITLE
Unexpected token in JSON when viewing History

### ISSUE THREAD

**Issue by vstakhov** [vstakhov/rspamd#1581]
_From @ScOut3R on April 6, 2017 4:22_

Hi,

just upgraded from 1.4.4 to 1.5.4 and I get the following error when trying to view History.

```
Uncaught SyntaxError: Unexpected token ? in JSON at position 2561
    at JSON.parse (<anonymous>)
    at https://rspamd/js/app/history.js:68:58
    at Array.map (native)
    at process_history_v2 (https://rspamd/js/app/history.js:68:26)
    at process_history_data (https://rspamd/js/app/history.js:356:16)
    at https://rspamd/js/app/history.js:434:33
    at Object.success (https://rspamd/js/app/rspamd.js:403:41)
    at i (https://rspamd/js/lib/jquery-3.1.1.min.js:2:27983)
    at Object.fireWith [as resolveWith] (https://rspamd/js/lib/jquery-3.1.1.min.js:2:28749)
    at A (https://rspamd/js/lib/jquery-3.1.1.min.js:4:14203)
```
Obviously the JSON response would be handy debug this issue, but I am not comfortable of sharing it here, but after removing the email addresses I am happy to provide it through a private channel.

_Copied from original issue: vstakhov/rspamd-interface#18_

**Comment by vstakhov** [comment]
On 06/04/17 05:22, Mate Gabri wrote:
> Hi,
> 
> just upgraded from 1.4.4 to 1.5.4 and I get the following error when
> trying to view History.
> 
> |Uncaught SyntaxError: Unexpected token ? in JSON at position 2561 at
> JSON.parse (<anonymous>) at https://rspamd/js/app/history.js:68:58 at
> Array.map (native) at process_history_v2
> (https://rspamd/js/app/history.js:68:26) at process_history_data
> (https://rspamd/js/app/history.js:356:16) at
> https://rspamd/js/app/history.js:434:33 at Object.success
> (https://rspamd/js/app/rspamd.js:403:41) at i
> (https://rspamd/js/lib/jquery-3.1.1.min.js:2:27983) at Object.fireWith
> [as resolveWith] (https://rspamd/js/lib/jquery-3.1.1.min.js:2:28749) at
> A (https://rspamd/js/lib/jquery-3.1.1.min.js:4:14203) |
> 
> Obviously the JSON response would be handy debug this issue, but I am
> not comfortable of sharing it here, but after removing the email
> addresses I am happy to provide it through a private channel.

You can send it to me (you can use my gpg key if you want to encrypt data).

**Comment by vstakhov** [comment]
That should be fixed now.

**Comment by RalfvdEnden** [comment]
I've backported the necessary changes to libucl and controller.c to 1.5.4, but unfortunately my history still shows a similar error as ScOut3R

**Comment by RvdE** [comment]
Disregard my previous comment. I've updated the freebsd port mail/rspamd-devel to revision d49b91d and the hirstory works fine now.
