### ISSUE TITLE
No analyze if ASN module don't respond

### ISSUE THREAD

**Issue by gauthierc** [vstakhov/rspamd#2033]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [x] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
rspamd                  1.6.6-4~stretch  amd64

### Operation system, CPU, memory and environment:
debian 9
4 vcpu
2 Go of Ram

### Description (Please provide a descriptive summary of the issue):

When ASN module can't contact asn.rspamd.com, the analyze fail with a timeout and any other check are not do. Every spam and virus are deliver in the mailbox with no error and score=0.0.

In rspamd.log file : 
lua; asn.lua:63: error querying dns: server fail
task; rspamd_task_timeout: processing of task timed out, forced processing

Solution for me : remove ASN module.

**Comment by vstakhov** [comment]
This means that your `dns -> timeout*retransmits` is higher than `task_timeout` in worker's configuration.

**Comment by gauthierc** [comment]
Thank you for the quick reply. I corrected my configuration.

**Comment by do18** [comment]
> This means that your `dns -> timeout*retransmits` is higher than `task_timeout` in worker's configuration.

I have not changed the defaults:

```
task_timeout = 8;
dns {
        timeout = 1;
        retransmits = 5;
        ...
}
```

But the issue (flag "ASN_FAIL (0)" set, no further scanning done) still occured. Here are the relevant log lines:

```
/var/log/rspamd/rspamd.log.1-2022-03-27 19:32:31 #1798(normal) <968b3b>; task; rspamd_message_parse: loaded message; id: <X@X.X>; queue-id: <F31E7920076>; size: 5938; checksum: <f29f1b6b9cb5e1ad3b885a1380ccd2ec>
/var/log/rspamd/rspamd.log.1-2022-03-27 19:32:33 #1798(normal) <968b3b>; task; rspamd_mime_part_detect_language: detected part language: de
/var/log/rspamd/rspamd.log.1-2022-03-27 19:32:33 #1798(normal) <968b3b>; task; rspamd_mime_part_detect_language: detected part language: de
/var/log/rspamd/rspamd.log.1-2022-03-27 19:32:33 #1798(normal) <968b3b>; task; rspamd_task_timeout: processing of task time out: 29.2s spent; 8.0s limit; forced processing
/var/log/rspamd/rspamd.log.1-2022-03-27 19:32:33 #1798(normal) <968b3b>; events; rspamd_session_cleanup: forced removed event on destroy: 00007FB5BF7774B8, subsystem: rspamd dns, scheduled from: ./src/libserver/dns.c:272
/var/log/rspamd/rspamd.log.1-2022-03-27 19:32:33 #1798(normal) <968b3b>; lua; asn.lua:72: error querying dns "X.X.X.X.asn.rspamd.com" on 127.0.0.1: query timed out
/var/log/rspamd/rspamd.log.1-2022-03-27 19:32:33 #1798(normal) <968b3b>; events; rspamd_session_cleanup: pending 0 uncancellable events
/var/log/rspamd/rspamd.log.1-2022-03-27 19:32:33 #1798(normal) <968b3b>; lua; greylist.lua:331: Score too low - skip greylisting
/var/log/rspamd/rspamd.log.1:2022-03-27 19:32:33 #1798(normal) <968b3b>; task; rspamd_task_write_log: id: <X@X.X>, qid: <F31E7920076>, ip: X.X.X.X, from: <X@X.X>, (default: F (no action): [0.00/15.00] [ASN_FAIL(0.00){X.X.X.X.asn.rspamd.com:query timed out;}]), len: 5938, time: 29282.794ms, dns req: 1, digest: <f29f1b6b9cb5e1ad3b885a1380ccd2ec>, rcpts: <X@X.X>, mime_rcpts: <X@X.X>
/var/log/rspamd/rspamd.log.1-2022-03-27 19:32:33 #1798(normal) <968b3b>; task; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 0 regexps matched, 172 regexps total, 0 regexps cached, 0B scanned using pcre, 0B scanned total
/var/log/rspamd/rspamd.log.1-2022-03-27 19:32:33 #1796(rspamd_proxy) <182b4b>; proxy; proxy_milter_finish_handler: finished milter connection
```

Any idea what might have happened here?
