### ISSUE TITLE
[1.7.4] fuzzy_check_timer_callback: got IO timeout with

### ISSUE THREAD

**Issue by andypl78** [vstakhov/rspamd#2238]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.4-2~jessie amd64
### Operation system, CPU, memory and environment:
Debian Jessie

### Description (Please provide a descriptive summary of the issue):

In log I have this:

> 2018-05-10 12:57:29 #31505(normal) <72165d>; task; fuzzy_check_timer_callback: got IO timeout with server 127.0.0.1(127.0.0.1), after 1 retransmits

fuzzy running:

> netstat -lnp |grep 11335
> tcp        0      0 127.0.0.1:11335         0.0.0.0:*               LISTEN      9326/rspamd: main p
> udp    12544      0 127.0.0.1:11335         0.0.0.0:*                           9326/rspamd: main p

### Configuration:

```
worker "fuzzy" {
    bind_socket = "127.0.0.1:11335";
    count = -1; # Disable by default
    .include "$CONFDIR/worker-fuzzy.inc"
    .include(try=true; priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/worker-fuzzy.inc"
    .include(try=true; priority=10) "$LOCAL_CONFDIR/override.d/worker-fuzzy.inc"
}

fuzzy_check {
    min_bytes = 1k; # Since small parts and small attachments causes too many FP
    timeout = 2s;
    retransmits = 1;
    rule "local" {
        algorithm = "mumhash";
        #servers = "rspamd.com:11335";
        servers = "127.0.0.1:11335";
        #encryption_key = "icy63itbhhni8bq15ntp5n5symuixf73s1kpjh6skaq4e7nx5fiy";
        symbol = "FUZZY_UNKNOWN";
        mime_types = ["application/*"];
        max_score = 20.0;
        read_only = no;
        skip_unknown = yes;
        fuzzy_map = {
            FUZZY_DENIED {
                max_score = 20.0;
                flag = 1;
            }
            FUZZY_PROB {
                max_score = 10.0;
                flag = 2;
            }
            FUZZY_WHITE {
                max_score = 2.0;
                flag = 3;
            }
        }
    }
    # Include dynamic conf for the rule
    .include(try=true,priority=5) "${DBDIR}/dynamic/fuzzy_check.conf"
    .include(try=true,priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/fuzzy_check.conf"
    .include(try=true,priority=10) "$LOCAL_CONFDIR/override.d/fuzzy_check.conf"
}


# Included from top-level .conf file

backend = "redis";

# For sqlite stuff
#backend = "sqlite";
#hash_file = "${DBDIR}/fuzzy.db";

expire = 30d;
allow_update = ["127.0.0.1"];

```

**Comment by vstakhov** [comment]
That should be fixed in 1.7.5.

**Comment by jcfernandez-890825** [comment]
I have version 1.7.5, problem still remains.

**Comment by oxpa** [comment]
1.7.6 still the same.
It looks like no fuzzy worker is spawned. 11335 is listened by the 'main' process which doesn't react to connection to 11335 (according to strace).

**Comment by oxpa** [comment]
It looks like that was my fault: redis server configuration has gone somehow. And error observed in logs:
```
rspamd[26219]: (fuzzy) <a4fde0>; main; rspamd_fork_worker: starting fuzzy process 26229 (1); listen on: *:11335 
rspamd[26219]: (fuzzy) <5mk4bi>; cfg; rspamd_fuzzy_backend_init_redis: cannot init redis backend for fuzzy storage
rspamd[26219]: (fuzzy) <a4fde0>; main; rspamd_fork_worker: starting fuzzy process 26230 (2); listen on: *:11335 
rspamd[26219]: (fuzzy) <a4fde0>; main; rspamd_fork_worker: starting fuzzy process 26228 (0); listen on: *:11335 
rspamd[26219]: (fuzzy) <5mk4bi>; cfg; rspamd_fuzzy_backend_init_redis: cannot init redis backend for fuzzy storage
rspamd[26219]: (fuzzy) start_fuzzy: cannot open backend: unknown error
rspamd[26219]: (fuzzy) <5mk4bi>; cfg; rspamd_fuzzy_backend_init_redis: cannot init redis backend for fuzzy storage
rspamd[26219]: (fuzzy) start_fuzzy: cannot open backend: unknown error
rspamd[26219]: (fuzzy) <a4fde0>; main; rspamd_fork_worker: starting fuzzy process 26231 (3); listen on: *:11335 
rspamd[26219]: (fuzzy) start_fuzzy: cannot open backend: unknown error
rspamd[26219]: (fuzzy) <5mk4bi>; cfg; rspamd_fuzzy_backend_init_redis: cannot init redis backend for fuzzy storage
rspamd[26219]: (fuzzy) start_fuzzy: cannot open backend: unknown error
```
The solution is to configure redis server explicitly for the worker:
```
# Included from top-level .conf file

backend = "redis";
servers = "localhost" # <- use proper server for fuzzy

# For sqlite stuff
#backend = "sqlite";
#hash_file = "${DBDIR}/fuzzy.db";

expire = 30d;
allow_update = ["127.0.0.1"];
```
